INSERT INTO tb_campos_os (label, type, tag) VALUES
('PRAÇA', 'text', 'input'),
('PROBLEMA ALEGADO', 'text', 'input'),
('DATA DO AGENDAMENTO', 'text', 'input'),
('PERÍODO', 'text', 'input'),
('VERIFICADO ALARME DO U2000', 'text', 'input'),
('SINAL ÓTICO: INFORMAR dBm', 'text', 'input'),
('CTO', 'text', 'input'),
('PORTA', 'text', 'input'),
('SSID', 'text', 'input'),
('SENHA', 'text', 'input'),
('ENDEREÇO ANTIGO', 'text', 'input'),
('ALTERADO O ENDEREÇO NO CADASTRO E O.S', 'text', 'input'),
('CLIENTE CIENTE DA POSSÍVEL TAXA', 'text', 'input'),
('( X ) COBRANÇA NA FATURA 1 DIAS', 'text', 'input'),
('VALOR TAXA: R$', 'text', 'input'),
('DESEJA OU NÃO ANTECIPAR', 'text', 'input'),
('PONTOS DE REFERÊNCIA', 'text', 'input'),
('CONTATO DO CLIENTE', 'text', 'input'),
('CONTATO(2) DO CLIENTE', 'text', 'input'),
('OBS:', 'text', 'input');
