INSERT INTO tb_campos_os (label, tipo_servico_id, type, tag) VALUES 
('ENDEREÇO ANTIGO', 3, 'text', 'textarea'),
('ALTERADO O ENDEREÇO NO CADASTRO E O.S', 3, 'text', 'input'),
('PRAÇA', 3, 'text', 'input'),
('DATA DE AGENDAMENTO', 3, 'date', 'input'),
('PERÍODO', 3, 'text', 'input'),
('CTO', 3, 'text', 'input'),
('PORTA', 3, 'text', 'input'),
('SSID', 3, 'text', 'input'),
('SENHA', 3, 'text', 'input'),
('PONTOS DE REFERÊNCIA', 3, 'text', 'textarea'),
('VALOR TAXA R$75 ( X ) COBRANÇA NA FATURA 1 DIAS', 3, 'text', 'input'),
('CONTATO DO CLIENTE', 3, 'text', 'input'),
('CONTATO(3) DO CLIENTE', 3, 'text', 'input'),
('OBS', 3, 'text', 'input');